# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    # "~/.config/alacritty/themes/themes/base16_default_dark.toml"
    #"~/.config/alacritty/themes/themes/monokai_pro.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
startup_mode = "Maximized"

[env]
term = "xterm-256color"

[font]
normal = { family = "MesloLGS NF" }
#normal = { family = "JetBrainsMono NF"}
size = 15

[keyboard]
bindings = [
    { key = "B", mods = "Command", action = "SpawnNewInstance" },
    { key = "'", mods = "Command", action = "Quit"},
    { key = "Back", mods= "Control", chars = "⌃⌫"},
    { key = ",", mods = "Command", chars = "⌘,"},
    { key = "e", mods = "Command", chars = "⌘e"},
    { key = "u", mods = "Command", chars = "⌘u"},
    { key = "u", mods = "Command|Shift", chars = "⌘U"},
    { key = "1", mods = "Command", chars = "⌘1"},
    { key = "h", mods = "Control", chars = "⌃h"},
    { key = "t", mods = "Control", chars = "⌃t"},
    { key = "h", mods = "Command", chars = "⌘h"},
    { key = "t", mods = "Command", chars = "⌘t"},
    { key = "n", mods = "Command", chars = "⌘n"},
    { key = "i", mods = "Command", chars = "⌘i"},
    { key = "h", chars = "h"}
]
