# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
[general]
import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
    #"~/.config/alacritty/themes/themes/base16_default_dark.toml"
    #"~/.config/alacritty/themes/themes/monokai_pro.toml"
    #"~/.config/alacritty/catppuccin-macchiato.toml"
    #"~/.config/alacritty/themes/themes/dark_pastels.toml"
]

[colors.primary]
background = "#1F2023"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS NF" }
size = 15

[keyboard]
bindings = [
    { key = "B", mods = "Command", action = "SpawnNewInstance" },
    { key = "'", mods = "Command", action = "Quit"},
    { key = "Enter", mods = "Command", chars = "⌘↵"},
    { key = "Back", mods= "Control", chars = "⌃⌫"},
    { key = ",", mods = "Command", chars = "⌘,"},
    { key = "e", mods = "Command", chars = "⌘e"},
    { key = "u", mods = "Command", chars = "⌘u"},
    { key = "u", mods = "Command|Shift", chars = "⌘U"},
    { key = "p", mods = "Command", chars = "⌘p"},
    { key = "d", mods = "Control", chars = "⌃d"},
    { key = "h", mods = "Control", chars = "⌃h"},
    { key = "t", mods = "Control", chars = "⌃t"},
    { key = "n", mods = "Control", chars = "⌃n"},
    { key = "d", mods = "Alt", chars = "⌥d"},
    { key = "h", mods = "Alt", chars = "⌥h"},
    { key = "t", mods = "Alt", chars = "⌥t"},
    { key = "n", mods = "Alt", chars = "⌥n"},
    { key = "j", mods = "Alt", chars = "⌥j"},
    { key = "k", mods = "Alt", chars = "⌥k"},
    { key = "l", mods = "Alt", chars = "⌥l"},

    { key = "d", mods = "Shift|Alt", chars = "⌥D"},
    { key = "h", mods = "Shift|Alt", chars = "⌥H"},
    { key = "t", mods = "Shift|Alt", chars = "⌥T"},
    { key = "n", mods = "Shift|Alt", chars = "⌥N"},
    { key = "j", mods = "Shift|Alt", chars = "⌥J"},
    { key = "k", mods = "Shift|Alt", chars = "⌥K"},
    { key = "l", mods = "Shift|Alt", chars = "⌥L"},

    { key = "n", mods = "Command", chars = "⌘n"},
    { key = "i", mods = "Command", chars = "⌘i"},
    { key = "w", mods = "Command|Shift", chars = "⌘W"},
    { key = "r", mods = "Command", chars = "⌘r"},
    { key = "r", mods = "Command|Shift", chars = "⌘R"},
    { key = "w", mods = "Command", chars = "⌘,"}
]
