# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
[general]
import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
    #"~/.config/alacritty/themes/themes/base16_default_dark.toml"
    #"~/.config/alacritty/themes/themes/monokai_pro.toml"
    #"~/.config/alacritty/catppuccin-macchiato.toml"
    #"~/.config/alacritty/themes/themes/dark_pastels.toml"
]

[colors.primary]
background = "#1F2023"

[window]
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS NF" }
size = 15

[keyboard]
bindings = [
    { key = "B", mods = "Command", action = "SpawnNewInstance" },
    { key = "'", mods = "Command", action = "Quit"},
    { key = "Enter", mods = "Command", chars = "⌘↵"},
    { key = "Back", mods= "Control", chars = "⌃⌫"},
    { key = ",", mods = "Command", chars = "⌘,"},
    { key = "e", mods = "Command", chars = "⌘e"},
    { key = "u", mods = "Command", chars = "⌘u"},
    { key = "u", mods = "Command|Shift", chars = "⌘U"},
    { key = "p", mods = "Command", chars = "⌘p"},
    { key = "h", mods = "Control", chars = "⌃h"},
    { key = "t", mods = "Control", chars = "⌃t"},
    { key = "h", mods = "Command", chars = "⌘h"},
    { key = "t", mods = "Command", chars = "⌘t"},
    { key = "n", mods = "Command", chars = "⌘n"},
    { key = "i", mods = "Command", chars = "⌘i"},
    { key = "w", mods = "Command|Shift", chars = "⌘W"},
    { key = "r", mods = "Command", chars = "⌘r"},
    { key = "r", mods = "Command|Shift", chars = "⌘R"}
]
